FROM registry.access.redhat.com/ubi8/openjdk-17:1.17-4 
USER root
WORKDIR /opt/app
COPY . /opt/app
RUN mvn clean install -f pom.xml
ARG JAR_FILE=target/spring-docker-simple-0.0.1-SNAPSHOT.jar    
CMD ["java","-jar","target/spring-docker-simple-0.0.1-SNAPSHOT.jar"]